In [1]:
!pip install transformers
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
!pip install git+https://git@github.com/SKTBrain/KoBERT.git@master
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.4 MB 5.1 MB/s 
     |████████████████████████████████| 596 kB 65.7 MB/s 
     |████████████████████████████████| 101 kB 12.8 MB/s 
     |████████████████████████████████| 6.6 MB 48.8 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/SKTBrain/KoBERT.git to /tmp/pip-install-_ky98g9l/kobert-tokenizer_d4137159326d42efafeb32bbd7caf43b
  Running command git clone -q https://github.com/SKTBrain/KoBERT.git /tmp/pip-install-_ky98g9l/kobert-tokenizer_d4137159326d42efafeb32bbd7caf43b
  Created wheel for kobert-tokenizer: filename=kobert_tokenizer-0.1-py3-none-any.whl size=4649 sha256=fd8790cffab2026658c6fc813bd39460ccf38c9007f45b

In [30]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
fonts-nanum is already the newest version (20170925-1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive/AI_Project

/content/drive/MyDrive/AI_Project


In [3]:
import pandas as pd
import numpy as np

trainset = pd.read_csv('trainset.csv')
testset = pd.read_csv('testset.csv')
validset = pd.read_csv('validset.csv')
label = pd.read_csv('label.csv')

label

0
0  놀람
1  분노
2  불안
3  슬픔
4  중립
5  행복
6  혐오

In [8]:
from transformers import BertForSequenceClassification, BertConfig
from kobert_tokenizer import KoBERTTokenizer
import torch

tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
config = BertConfig.from_pretrained('skt/kobert-base-v1')
num_labels = 7
config.num_labels = num_labels
model = BertForSequenceClassification.from_pretrained('skt/kobert-base-v1', config=config)
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

model.to(device)
torch.cuda.is_available()

Downloading:   0%|          | 0.00/363k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/244 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/432 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.


Downloading:   0%|          | 0.00/535 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/352M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at skt/kobert-base-v1 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


True

In [11]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(output_dir="test_trainer",
                                  num_train_epochs=5,
                                  evaluation_strategy="epoch",
                                  per_device_train_batch_size=64)

In [10]:
tokenizer("일기를 씁시다.", truncation=True, padding=True)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


{'input_ids': [2, 3803, 5573, 517, 6783, 6705, 5782, 54, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [11]:
tokenizer.batch_encode_plus("<br>일기를 씁시다")

{'input_ids': [[2, 630, 3], [2, 517, 380, 3], [2, 517, 435, 3], [2, 632, 3], [2, 3803, 3], [2, 1258, 3], [2, 517, 6116, 3], [2, 3], [2, 517, 6783, 3], [2, 2959, 3], [2, 1562, 3]], 'token_type_ids': [[0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0, 0], [0, 0], [0, 0, 0, 0], [0, 0, 0], [0, 0, 0]], 'attention_mask': [[1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1, 1], [1, 1], [1, 1, 1, 1], [1, 1, 1], [1, 1, 1]]}

In [12]:
text = ["안녕하세요", "반갑습니다.", "일기 쓰는 것은 즐겁다. 그렇지만 조금 귀찮아."]

tokenizer(text)

{'input_ids': [[2, 3135, 5724, 7814, 3], [2, 2207, 5345, 6701, 54, 3], [2, 3803, 5561, 3084, 5760, 910, 517, 7313, 5397, 5782, 54, 1205, 6150, 4164, 1174, 7396, 6797, 54, 3]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [13]:
tokenizer.batch_encode_plus(text)

{'input_ids': [[2, 3135, 5724, 7814, 3], [2, 2207, 5345, 6701, 54, 3], [2, 3803, 5561, 3084, 5760, 910, 517, 7313, 5397, 5782, 54, 1205, 6150, 4164, 1174, 7396, 6797, 54, 3]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [13]:
# train_encodings = tokenizer.batch_encode_plus(trainset['Sentence'])
# val_encodings = tokenizer.batch_encode_plus(validset['Sentence'])
# test_encodings = tokenizer.batch_encode_plus(testset['Sentence'])

train_encodings = tokenizer(trainset['Sentence'].tolist(), truncation=True, padding=True, max_length=512, return_tensors="pt")
val_encodings = tokenizer(validset['Sentence'].tolist(), truncation=True, padding=True, max_length=512, return_tensors="pt")
test_encodings = tokenizer(testset['Sentence'].tolist(), truncation=True, padding=True, max_length=512, return_tensors="pt")

In [14]:
import torch

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)
    
train_dataset = Dataset(train_encodings, trainset['encoded_label'].tolist())
val_dataset = Dataset(val_encodings, validset['encoded_label'].tolist())
test_dataset = Dataset(test_encodings, testset['encoded_label'].tolist())

In [15]:
from datasets import load_metric

metric = load_metric("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [17]:
trainer = Trainer(model=model,
                  args=training_args,
                  train_dataset=train_dataset,
                  eval_dataset=val_dataset,
                  compute_metrics=compute_metrics)

trainer.train()

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 136842
  Num Epochs = 5
  Instantaneous batch size per device = 64
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 1
  Total optimization steps = 10695


Saving model checkpoint to test_trainer/checkpoint-500
Configuration saved in test_trainer/checkpoint-500/config.json
Model weights saved in test_trainer/checkpoint-500/pytorch_model.bin
Saving model checkpoint to test_trainer/checkpoint-1000
Configuration saved in test_trainer/checkpoint-1000/config.json
Model weights saved in test_trainer/checkpoint-1000/pytorch_model.bin
Saving model checkpoint to test_trainer/checkpoint-1500
Configuration saved in test_trainer/checkpoint-1500/config.json
Model weights saved in test_trainer/checkpoint-1500/pytorch_model.bin
Saving model checkpoint to test_trainer/checkpoint-2000
Configuration saved in test_trainer/checkpoint-2000/config.json
Model weights saved in test_trainer/checkpoint-2000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 17106
  Batch size = 8
Saving model checkpoint to test_trainer/checkpoint-2500
Configuration saved in test_trainer/checkpoint-2500/config.json
Model weights saved in test_trainer/checkpoint-2500/

TrainOutput(global_step=10695, training_loss=0.6939162936930681, metrics={'train_runtime': 21816.0039, 'train_samples_per_second': 31.363, 'train_steps_per_second': 0.49, 'total_flos': 6.6808489108815e+16, 'train_loss': 0.6939162936930681, 'epoch': 5.0})

In [18]:
trainer.predict(test_dataset)

***** Running Prediction *****
  Num examples = 17105
  Batch size = 8


PredictionOutput(predictions=array([[-1.1602546 ,  1.0730047 , -1.3574861 , ..., -2.4661148 ,
        -2.0656548 , -0.83283377],
       [-0.26374614,  4.1058235 , -0.84387064, ..., -2.3154883 ,
        -1.9542767 ,  4.454399  ],
       [-3.6544802 ,  2.4854922 , -2.3465056 , ...,  3.5955546 ,
        -2.6580968 ,  2.1560056 ],
       ...,
       [ 0.33122715, -0.92515486, -2.7544577 , ...,  4.4150734 ,
        -1.2547761 , -2.8126035 ],
       [-1.4024093 ,  5.344571  , -1.2209622 , ...,  0.68961734,
        -2.8177555 ,  0.22311069],
       [ 1.8898264 , -1.409481  , -2.2761145 , ...,  6.288574  ,
        -1.4596444 , -1.9005525 ]], dtype=float32), label_ids=array([3, 1, 4, ..., 4, 1, 4]), metrics={'test_loss': 1.1250156164169312, 'test_accuracy': 0.6726688102893891, 'test_runtime': 352.5749, 'test_samples_per_second': 48.515, 'test_steps_per_second': 6.067})

In [19]:
trainer.save_model('model')

Saving model checkpoint to model
Configuration saved in model/config.json
Model weights saved in model/pytorch_model.bin


In [20]:
test_model = BertForSequenceClassification.from_pretrained('/content/model', local_files_only=True)
test_model.to(device)

def prediction(predict_sentence):
  if type(predict_sentence) == str:
      data = [predict_sentence]
  else:
      data = predict_sentence

  inputs = tokenizer(data, return_tensors='pt')
  inputs.to(device)

  with torch.no_grad():
        logits = model(**inputs).logits

  predicted_class_id = logits.argmax().item()
  output = model.config.id2label[predicted_class_id]
    
  if output == "LABEL_0":
    return "놀람"
  elif output == "LABEL_1":
    return "분노"
  elif output == "LABEL_2":
    return "불안"
  elif output == "LABEL_3":
    return "슬픔"
  elif output == "LABEL_4":
    return "평범"
  elif output == "LABEL_5":
    return "행복"
  elif output == "LABEL_6":
    return "혐오"

loading configuration file /content/model/config.json
Model config BertConfig {
  "_name_or_path": "skt/kobert-base-v1",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "author": "Heewon Jeon(madjakarta@gmail.com)",
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "kobert_version": 1.0,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolut

In [21]:
prediction("모의 코딩테스트도 치고 자소서도 써야 함")

'불안'

In [16]:
test_model = BertForSequenceClassification.from_pretrained('./model', local_files_only=True)
test_model.to(device)

trainer = Trainer(model=test_model,
                  args=training_args,
                  train_dataset=train_dataset,
                  eval_dataset=val_dataset,
                  compute_metrics=compute_metrics)

In [17]:
test = trainer.predict(test_dataset)

***** Running Prediction *****
  Num examples = 17105
  Batch size = 8


In [18]:
pred = test.label_ids

In [24]:
from sklearn.metrics import confusion_matrix

confusion_matrix(testset['encoded_label'], pred)

array([[1826,    0,    0,    0,    0,    0,    0],
       [   0, 2345,    0,    0,    0,    0,    0],
       [   0,    0, 1604,    0,    0,    0,    0],
       [   0,    0,    0, 3260,    0,    0,    0],
       [   0,    0,    0,    0, 5300,    0,    0],
       [   0,    0,    0,    0,    0, 1825,    0],
       [   0,    0,    0,    0,    0,    0,  945]])

In [20]:
test

PredictionOutput(predictions=array([[-1.155884  ,  1.322548  , -1.2007717 , ..., -2.4799788 ,
        -2.5375347 , -0.8794909 ],
       [-1.5912974 ,  4.0527916 , -0.83689314, ..., -1.1350601 ,
        -2.2701883 ,  4.3601217 ],
       [-3.5350358 ,  3.2441475 , -3.3455176 , ...,  3.7477596 ,
        -0.9901037 ,  0.20652834],
       ...,
       [ 0.84176344, -1.3072754 , -2.600108  , ...,  5.0413504 ,
        -1.8430637 , -2.6864398 ],
       [-0.15375309,  5.361841  , -2.0385537 , ...,  0.89115936,
        -2.2943149 , -1.5960497 ],
       [ 1.0602455 , -1.4973918 , -1.7553849 , ...,  6.528688  ,
        -1.3817096 , -2.435098  ]], dtype=float32), label_ids=array([3, 1, 4, ..., 4, 1, 4]), metrics={'test_loss': 1.090489149093628, 'test_runtime': 340.509, 'test_samples_per_second': 50.234, 'test_steps_per_second': 6.282})

In [27]:
from sklearn.metrics import confusion_matrix

confusion_matrix(testset['encoded_label'], test.predictions.argmax(axis=1))

array([[ 952,  120,  149,  208,  290,   65,   42],
       [ 133, 1393,   74,  268,  284,   28,  165],
       [ 142,   99,  976,  248,   99,   27,   13],
       [ 178,  225,  240, 2243,  268,   82,   24],
       [ 283,  220,   79,  343, 4134,  153,   88],
       [  53,   21,   23,   70,  162, 1475,   21],
       [  46,  246,   25,   70,  149,   23,  386]])

In [26]:
test.predictions.argmax(axis=1)

array([3, 6, 4, ..., 4, 1, 4])

In [29]:
(testset['encoded_label'] == test.predictions.argmax(axis=1)).sum() / len(testset)

0.675767319497223

In [21]:
pred[:10]

array([3, 1, 4, 1, 3, 1, 1, 5, 1, 4])

In [22]:
testset['encoded_label'][:10]

0    3
1    1
2    4
3    1
4    3
5    1
6    1
7    5
8    1
9    4
Name: encoded_label, dtype: int32

In [11]:
len(testset)

17105